apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: test-server
  template:
    metadata:
      labels:
        component: test-server
    spec:
      containers:
        - name: test-server
          image: wemeter/test-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-ip-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
