on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: wemetercontainerregistry.azurecr.io
        username: ${{ secrets.acr_wemetercontainerregistry_username }}
        password: ${{ secrets.acr_wemetercontainerregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "." -t wemetercontainerregistry.azurecr.io/wemeter:${{ github.sha }}
        docker push wemetercontainerregistry.azurecr.io/wemeter:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_wemeter_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep wemeter8697 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace wemeter8697`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: wemeter8697
        container-registry-url: wemetercontainerregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_wemetercontainerregistry_username }}
        container-registry-password: ${{ secrets.acr_wemetercontainerregistry_password }}
        secret-name: wemeterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: wemeter8697
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          wemetercontainerregistry.azurecr.io/wemeter:${{ github.sha }}
        imagepullsecrets: |
          wemeterdockerauth